CREATE TABLE Users(
	id 			BIGINT AUTO_INCREMENT PRIMARY KEY,
	fullname 	VARCHAR(50) NOT NULL,
	email 		VARCHAR(150) NOT NULL UNIQUE,
	phoneNumber VARCHAR(20) NOT NULL UNIQUE,
	address 	VARCHAR(200) NOT NULL,
	password 	VARCHAR(32) NOT NULL,
	avatar		VARCHAR(100),
	roleId 		INT, 
	createdAt 	TIMESTAMP,
	updatedAt 	TIMESTAMP,
	FOREIGN KEY (roleId) REFERENCES Role(id)	
);