CREATE TABLE ProductDetail(
	id						BIGINT AUTO_INCREMENT PRIMARY KEY,
	status  				VARCHAR(20) NOT NULL,
	origin 					VARCHAR(50) NOT NULL,
	collection 				VARCHAR(100),
	gender					INT NOT NULL,
	size					VARCHAR(50) NOT NULL,
	style					VARCHAR(100),
	machineType 			VARCHAR(100) NOT NULL,
	dial 					VARCHAR(50),
	glassMaterial 			VARCHAR(100) NOT NULL,
	caseMaterial 			VARCHAR(100),
	strapMaterial 			VARCHAR(100),
	shape 					VARCHAR(50),
	thickness 				VARCHAR(50),
	waterResistance 		VARCHAR(50) NOT NULL,
	benzel 					VARCHAR(50),
	energyStorage 			VARCHAR(50),
	weight 					VARCHAR(20),
	feature 				VARCHAR(100),
	domesticWarranty		VARCHAR(50) NOT NULL,
	internationalWarranty 	VARCHAR(50),
	note					VARCHAR(500),
	detailDescription		LONGTEXT,
	FOREIGN KEY(id) REFERENCES Products(id)
);